### ISSUE TITLE
geordi rspec no longer works in geordi 4.0.0

### ISSUE THREAD

**Issue by KD6-3** [makandra/geordi#109]
`geordi rspec` produces following error in a rails 6 project.

```
NameError:
  uninitialized constant FactoryBot
```

`bundle exec rspec` or `bundle exec bin/rspec` works as expected. `bin/rake parallel:spec` doesn't get executed in the bundle context and might be the cause of this problem.

My rake binstub looks like this.

```
#!/usr/bin/env ruby
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
require_relative '../config/boot'
require 'rake'
Rake.application.run
```

**Comment by denzelem** [comment]
As a reminder: We should add a0b82fefcd0b5727039496e6174d52d0ec7f3e88 to the Changelog, so other developer can locate such issues faster.

We already broke some projects when switching from geordi's setup to `bin/setup`. This happens every time, the developers of a project don't use the bin stubs. Beside fixing the bin stub, deleting it is also a valid option.

@KD6-3 Thanks for reporting the issue, we will have a look at it!

**Comment by denzelem** [comment]
@KD6-3 You can fix this issue in two ways:

**Option 1 (preferred):**

Adjust you binstubs to work with your project. For a Rails Project you usually want to use Spring + Bundle for each bin stub.

Example for the rake binstub:

```
bundle binstubs rake --force
spring binstub rake
```

Check the diff carefully, if you use a modified binstub.

**Option 2:**

Delete `bin/rake` if you don't want to use it anyway. Geordi will use a fallback, that works,  if the binstub is not present.
