### ISSUE TITLE
Add a generic deploy command

### ISSUE THREAD

**Issue by codener** [makandra/geordi#11]
Proposed functionality:

- option `--branch`: The branch to deploy from, default: `master`
- option `--stage`: The stage to deploy to, default: `staging`

The command will also deliver Pivotal Tracker stories.

**Comment by henning-koch** [comment]
Some thoughts on that:

- I only ever want to deploy to `staging` and `production`. This should be made as easy as possible.
- I wouldn't want a deployment command to make changes in PT, at least not by default.

**Comment by codener** [comment]
Implemented in 1.2.0 (without connecting to PT).
