### ISSUE TITLE
Use new Ruby version

### ISSUE THREAD

**Issue by kajatiger** [makandra/geordi#118]
Is there a reason, why the ruby version is set to 2.5? If not, I suggest to move it up to at least 2.6

**Comment by codener** [comment]
The Ruby version in .ruby-version is only relevant in development. Please see .travis.yml for _supported_ versions of Ruby.

You are free to switch to a different Ruby version in development.

**Comment by kajatiger** [comment]
In development I had to switch to 2.6 because otherwise the tests would fail. That's why I wondered if there is a reason for 2.5 in the ruby version file. Is there one?

**Comment by codener** [comment]
If tests break in 2.5, they must be fixed. Geodi officially supports all 2.* versions. Which tests broke?

We're updating the .ruby-version file occasionally. Since Geordi supports Ruby 2.*, there is no point in keeping it bleeding edge.

**Comment by kajatiger** [comment]
I would say that 2.6 is certainly not bleeding edge anymore. On master the failing tests with Ruby 2.5.1 are the following:
```
Failing Scenarios:
cucumber features/cucumber.feature:232 # Scenario: Specifying a firefox version to use
cucumber features/cucumber.feature:246 # Scenario: Running all cucumber features matching a given string
cucumber features/firefox.feature:5 # Scenario: Running a command with VNC set up
cucumber features/firefox.feature:14 # Scenario: The command is aliased as "chrome"
cucumber features/firefox.feature:32 # Scenario: A .firefox-version file with "system" is ignored (legacy support)
```

**Comment by codener** [comment]
Thanks for the notification: we found our Travis config is broken. Thus, the `cucumber` command was broken in master but has been fixed. Firefox failures could not be reproduced.

I used the opportunity to update development dependencies. Ruby is unchanged, as Geordi needs to support a range of Ruby versions anyway. All tests are green now on our machines.
