### ISSUE TITLE
Scenarios marked with @solo are non properly handled in linear test runs

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#119]
Geordi comes with a Cucumber tag `@solo` that allows me to mark features that should always run isolated before the rest.

Lets have a look at this sample: `example.feature`
```
Feature: Example

  Scenario: Foo

  @solo
  Scenario: Bar
```

When I run my entire test suite with `geordi cucumber`, it works as intended: Scenario "Bar" is run separately.
**This does not work when I run just the feature alone, in a non-parallel way.**

```
$geordi cucumber features/example.feature
> # Running @solo features
> All features tagged with @solo
> Run `geordi vnc` to view the Selenium test browsers
> bundle exec cucumber features/example.feature --format pretty --backtrace --tags @solo
> Using the default profile...
> Feature: Example
>   @solo
>   Scenario: Bar
..
> # Running features
> Only: features/example.feature
> Run `geordi vnc` to view the Selenium test browsers
> **bundle exec cucumber features/example.feature --format pretty --backtrace**
> Using the default profile...
> Feature: Example
>   Scenario: Foo
>
>   **@solo**
>   Scenario: Bar
```

As you can see, in this case the `@solo` Feature was executed twice, as it is not excluded from the normal test run.

**Comment by codener** [comment]
The preliminary `@solo` run should only happen when a consecutive parallel run is intended. In serial execution this tag has no point.

**Comment by makmic** [comment]
I totally see your point. Actually I had the case today where a scenario was failing in the serial execution, but not in the preliminary `@solo` run.. that's pretty weird.
I'll put my PR on hold until I get this sorted out.
