### ISSUE TITLE
Eurest 404 Not Found

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#12]
```
geordi eurest
```
--2015-05-08 15:03:41--  http://www.eurest-extranet.de/eurest/export/sites/default/sigma-technopark/de/downloads/Sigma_KW19.pdf
Resolving www.eurest-extranet.de (www.eurest-extranet.de)... 195.50.176.176
Connecting to www.eurest-extranet.de (www.eurest-extranet.de)|195.50.176.176|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-05-08 15:03:41 ERROR 404: Not Found.

**Comment by codener** [comment]
I know it's broke... They seem to change their file naming every other week. You are welcome to submit a patch!

**Comment by foobear** [comment]
I just released 1.1.4 which will work until they change their filenames again.
