### ISSUE TITLE
Stop Spring for "geordi update"

### ISSUE THREAD

**Issue by codener** [makandra/geordi#121]
On Rails 6, I frequently see this error when using `geordi update` during migrations:
```
/home/me/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies/zeitwerk_integration.rb:14:in `rescue in block in clear': reloading is disabled because config.cache_classes is true (RuntimeError)
```
I suggest we stop Spring in `geordi update`, where code changes + migrations almost certainly provoke this error. 

While we could run it every time we migrate, we'd loose the performance boost Spring generally gives. What do you think about checking if `zeitwerk` is in use instead of stopping Spring categorically?

**Comment by denzelem** [comment]
As `zeitwerk` seems to be the new default I think it would make sense to have this in geordi directly.

Another option would be to allow `geordi update` to be overwritten by a binstub in `bin/update`. Not saying that this an better option, but an alternative approach if projects are configured differently.

**Comment by codener** [comment]
Turns out it wasn't Geordi's fault, but a misconfiguration of the project. Every other run of `bin/rake db:migrate RAILS_ENV=test` would fail similarly.

See https://github.com/rails/spring/issues/598 and https://makandracards.com/makandra/487730-rails-6-zeitwerk-spring-and-cache_classes-true.
