### ISSUE TITLE
compress dumps created on deployments

### ISSUE THREAD

**Issue by ctriegg-mak** [makandra/geordi#130]
It would be good if the dumps created when deploying are stored compressed. 

For MySQL dumps this could be done with `gzip` as it's available on most servers. 
It would be nice if the compression tool/command could be configured. Then more faster compress tools like `zstd` could be used if available (for e.g. on makandra servers). 

PostgreSQL dumps could be created with `pg_dump -F c` which will store the dump in the PostgreSQL custom format which could provide more benefits ([dumping and restoring PostgreSQL databases](https://makandracards.com/operations/44755-dumping-and-restoring-postgresql-databases)) and can easily [converted to textdumps](https://makandracards.com/operations/65315-convert-postgre) if necessary. The custom format is compressed by default.

**Comment by denzelem** [comment]
Thanks @ctriegg-mak for the input. We need to discuss this topic next week. Currently we had the following outcomes:

* It is nice to always compress PostgreSQL, as it detected the compression on the restore automatically. But this does not work for MySQL with gzip, so it would break the backwards compatibility for `geordi dump -l` with dumps that are not compresses.
* We thought about flags like `--compression-tool`, but this is strange when it only applies to MySQL
* We are not sure how easy it is to restore a dump, when the compression tool in case of MySQL is unknown

**Comment by ctriegg-mak** [comment]
Couldn't havethe dumps a file ending which indicates the format? 

For e.g.

- `foo.mysqldump`
- `foo.mysqldump.gzip`
- `foo.myqldump.zstd`
- `foo.pgdump`

**Comment by makmarius** [comment]
It is possible to query the file as to "what it is":

```
$ file foo.sql 
foo.sql: ASCII text
$ file foo.zst 
foo.zst: Zstandard compressed data (v0.8+), Dictionary ID: None
$ file foo.gz 
foo.gz: gzip compressed data, was "foo", last modified: Thu Nov 19 09:24:36 2020, from Unix, original size modulo 2^32 0
$ file foo.pgdump 
foo.pgdump: PostgreSQL custom database dump - v1.13-0
```

So via a small lookup table it could be easy to figure out which tool to use and raise an error should the necessary tool to decompress not be available.

**Comment by codener** [comment]
@ctriegg-mak could you illustrate the use case for this? I understand that compressed dumps take up less space, but is disk space that much of an issue? I am afraid the complexity this adds is not justified by the benefits.

**Comment by ctriegg-mak** [comment]
@codener 
There are multiple benefits: Smaller dumps are better for transferring and will have a smaller impact on disk I/O when the compression happens on the fly. CPU usage is insignificant in comparison when a modern compression algorithm (like `zstd`) is used. 

But one the most important benefit is the much smaller size. This can be important event if dumps on the server are kept only for a small time, for e.g. multiple consecutive deploys follow in a short time or if the database is very big. In some cases the server can run out of available disk space so fast that there is not enough time to respond and intervene. The compression can make a huge difference. I've just compressed a `4.4G` MySQL dump to `67M` with `gzip`.

**Comment by codener** [comment]
Meanwhile, I noticed Geordi already has compression support: https://github.com/makandra/geordi/commit/45ae05c49d70958aa252ed5513ca6abcd656714b

Could you just use that?

**Comment by ctriegg-mak** [comment]
I've never seen compressed dumps in the `~/dumps` directory (except for PostgreSQL dumps, which are compressed by default). I don't think that this feature is widely-used. Maybe it's a good option to enable compression of dumps by default.

**Comment by triskweline** [comment]
I solved this in my project by removing dumps older than 24 hours.

I only care about those dumps in the 5 minutes after deployment, in case a migration breaks it.

```ruby
namespace :db do
  desc 'Remove dumps older than 24 hours'
  task :clean_dumps, :roles => :db, :only => { :primary => true } do
    run "find ~/dumps/* -mtime +0 -delete"
  end
end
  
before "deploy:update_code", "db:clean_dumps"
```

**Comment by codener** [comment]
We decided to keep this out of Geordi and remove stale dumps instead. Either during deployment with the above task, or regularly with a cronjob.
