### ISSUE TITLE
Remove auto-bundling from `geordi shell` and `geordi console`

### ISSUE THREAD

**Issue by triskweline** [makandra/geordi#136]
We're maintaining old projects inside a Docker container because we cannot install old Rubies on modern Ubuntus.

We want to keep using `geordi shell` and `geordi console`, but these commands don't work in a Docker container that have no SSH agent.

We could use geordi outside the docker container, but the shell and console commands automatically bundle. This will fail because there is no Ruby to bundle into outside Docker.

It would be good to remove auto-bundling, at least for these two commands.

Since this affects old projects in particular this change would need to be backported to the last Geordi version that supports Ruby 1.8.7.

**Comment by triskweline** [comment]
Apparently Geordi already forwards the SSH agent into the container.

I would still suggest that we remove auto-bundling for these commands. There is no need to bundle to open a shell or console on a remote server, and I often use these commands for projects that I haven't setup locally yet.

**Comment by kratob** [comment]
It's a tiny bit more complicated for `geordi console` that it looks at first, since geordi uses `bundle list` to determine the Rails version, which in turn determines whether to run `script/console` or similar.

I suggest either
- using something like
  ```
  require 'bundler'
  lock_file = Bundler::LockfileParser.new(Bundler.read_file(Bundler.default_lockfile))
  lock_file.specs.detect { |spec| spec.name == gem_name }&.version
  ```
- or detecting the rails version via `bundle list` on the remote

**Comment by triskweline** [comment]
Could we use `script/console` if that file exists, and `rails console` otherwise?

**Comment by kratob** [comment]
There are other differences that are not as easiliy detectable, and I feel adding a mechanism to detect a gem version without bundling might be useful in other contexts as well.

**Comment by codener** [comment]
I assume bundling was introduced for the local Rails console opened by `geordi console`. It should not happen where bundling is not required, so we'll improve that.
