### ISSUE TITLE
Geordi breaks if capistrano 3 gem is installed

### ISSUE THREAD

**Issue by stemps** [makandra/geordi#14]
Geordi is bypassing bundler and as a result, gems get loaded "as they are found" without the version control of bundler.

This results in geordi breaking with the following error if the Capistrano 3 gem is installed and happens to be loaded:

```
# Opening a Rails console on staging
/Users/simons/projects/liefery/liefery-backend/.gems/gems/geordi-1.1.4/lib/geordi/capistrano_config.rb:44:in `load_capistrano_config': uninitialized constant Capistrano (NameError)
        from /Users/simons/projects/liefery/liefery-backend/.gems/gems/geordi-1.1.4/lib/geordi/capistrano_config.rb:13:in `initialize'
```

Ideally geordi should respect the version of capistrano (and other gems) as specifiled in the `Gemfile`.

**Comment by bitboxer** [comment]
:+1: for this. Sadly we currently have to switch to capistrano 3 because rails 4.2.2 does not play nice with older version of the sass gem

**Comment by henning-koch** [comment]
This should get fixed when we do https://github.com/makandra/geordi/issues/8 .

**Comment by codener** [comment]
This is still an issue, we should fix this soon as more and more users will have Capistrano 3 installed.
