### ISSUE TITLE
Add the --single-transaction option to dumple

### ISSUE THREAD

**Issue by jakobscholz** [makandra/geordi#142]
When big MySQL databases are dumped, they can not be accessed by the running application. This can be fixed by adding a `--single-transaction` option to the dumple script? I think, this can be even default behavior. The daily backup of our databases also uses this flag so there are no concerns.

https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html#option_mysqldump_single-transaction

**Comment by triskweline** [comment]
Vote to make this the default when it's good enough for our backups. If it's an option we need to fix every single `Capfile` for this to have an effect.

All our apps with non-trivial databases are offline for minutes whenever we deploy, this change could remedy this.
