### ISSUE TITLE
VNC swallows some characters

### ISSUE THREAD

**Issue by codener** [makandra/geordi#143]
Turns out [key mapping in VNC is quite an issue](https://www.google.com/search?q=vnc+keyboard+mapping+issues). Unfortunately, tightvnc introduced in f62cb693f27e2bb3da6153c39008d942432f0519 seems to have more issues than its predecessor, i.e. it may press return when a test types a space.

Todo: find a VNC server with less to no key mapping issues.

**Comment by denzelem** [comment]
VNC will not be supported in geordi anymore. Please see #151 for further details.
