### ISSUE TITLE
Option to limit number of test processes

### ISSUE THREAD

**Issue by triskweline** [makandra/geordi#147]
I have a lot of issues with test failures during parallel tests run. The issues become less severe when my PC is less busy. Because of this I would like the parallel test run to keep some of my CPUs idle.

Could geordi add an option to limit the number of test processes for the `test`, `rspec` and `cucumber` commands? When using the `parallel_tests` binary directly I can control this with the `-n` switch, but currently Geordi has no way to forward that switch.

**Comment by denzelem** [comment]
@triskweline Parallel tests supports this setting as an environment variable, too. So you should be able to limit the number of used CPUs like this:

```
PARALLEL_TEST_PROCESSORS=6 geordi cucumber
```

Is this enough for you or do you think this should be build into geordi as pass through parameter to parallel tests?

**Comment by triskweline** [comment]
It's enough for me.

I suggest that we document this. I couldn't find this even after going through the code of parallel_tests.
