### ISSUE TITLE
Loading dump from a local file explicitly should not delete that file

### ISSUE THREAD

**Issue by foobear** [makandra/geordi#148]
I understand that `geordi dump staging -l` loads a remote dump, sources it, and deletes the downloaded dump file afterwards.

However, `geordi dump -l path/to/some.dump` also deletes that file. I do not want to lose my local files.

Also, it would be nice to have a switch to make `geordi dump staging -l` keep the local file. That would allow keeping a single command and not having to use `geordi dump staging` + `geordi dump -l tmp/staging.dump` if I want to keep the downloaded dump file to source multiple times.

**Comment by codener** [comment]
Deleting dump files on explicit loading is not intended, I'll fix that.

However, I'll not add a switch for now. Someone who just needs their local database to hold the data of a remote one will use a single `geordi dump $stage --load` and not leave data traces behind. In contrast, someone who is interested in keeping a dump file for multiple loadings will use `geordi dump --load $file` anyway and can afford a separate command to fetch the file in the first place.
