### ISSUE TITLE
Dump command fails when there is no password set in database.yml

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#16]
Error: ```/home/me/.rvm/gems/ruby-2.1.5/gems/geordi-1.1.4/lib/geordi/dump_loader.rb:24:in `mysql_command': no implicit conversion of nil into String (TypeError)```

Root: https://github.com/makandra/geordi/blob/master/lib/geordi/dump_loader.rb#L24

**Comment by denzelem** [comment]
Workaround: Set `password` in database.yml to empty string: `password: ''`

**Comment by codener** [comment]
Also, when using `dump` with a PostgreSQL database, the `--username` argument should be omitted if the `username:` key is missing in database.yml.

**Comment by codener** [comment]
Similar when the `host:` key is missing.
