### ISSUE TITLE
"geordi shell" makes wrong assumptions when commenting out lines

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#162]
Given this `config/deploy/production.rb`:

```text
server 'app01.example.com', user: 'new_user'
# server 'app02.example.com', user: 'old_user'
```
`geordi shell production` tries to connect to `old_user@app01.example.com`, even though the second line is commented out. Even if it would be commented in, mixing the two lines does not seem right to me.

**Comment by codener** [comment]
Released as 6.1.0.
