### ISSUE TITLE
Missing thor runtime dependency

### ISSUE THREAD

**Issue by dastra-mak** [makandra/geordi#164]
In 37cca9a thor was removed as a runtime dependency. The code, however, heavily relies on thor.
Was this a conscious decision or a mistake?

One could argue that the Util class is smart enough to install missing required gems, but the `installing_missing_gems` method is blocking and waiting for user input. This is pretty inconvenient for CI runs.

**Comment by brunosedler** [comment]
We'll look into it. Meanwhile you could use an older version.
