### ISSUE TITLE
Geordi should always download the latest patch version for the corresponding major version

### ISSUE THREAD

**Issue by Denionysos** [makandra/geordi#170]
At the moment the command `geordi chromedriver-update` will find and install the matching chromedriver for the currently installed Chrome. But the command should also check if there are new patch versions for the current major version and then install them. This may fix issues that have appeared in the current major version.

E.g.
If the last stable release of the chrome driver is version 98.0.4758.**80** and I'm currently using Chromedriver 98.0.4758.**48**. Then `geordi chromedriver-update` should update my chromedriver to version 98.0.4758.**80**

**Comment by denzelem** [comment]
Released in Version [6.2.0](https://github.com/makandra/geordi/commit/e2b90b5ae29ba5b339b8f53bc6a94b356ddb9594).

/cc @niklas-hasselmeyer
