### ISSUE TITLE
Disable multi-line autocomplete by default

### ISSUE THREAD

**Issue by vrandr** [makandra/geordi#176]
Pasting in IRB 1.2+ is very slow. See these cards for further infos:

- https://makandracards.com/makandra/512584-irb-s-multi-line-autocomplete-and-how-to-disable-it
- https://makandracards.com/makandra/490022-how-to-fix-pasting-in-irb-1-2+-is-very-slow#section-option-2-disable-by-default

Can you disable the IRB multiline feature by calling `rails console -- --nomultiline` in https://github.com/makandra/geordi/blob/master/lib/geordi/util.rb#L86-L94?

This is supported. See https://github.com/rails/rails/issues/39909 for details.

**Comment by Denionysos** [comment]
> Is there any decision on this issue, if this will be implemented in geordi?

Yes, we have decided to implement the proposal. The change will come in the next days

**Comment by codener** [comment]
_Copied from PR:_

I tried geordi console on Ruby 2.7 with IRB 1.4.1 locally and IRB 1.2.6 on the Server. Unfortunately, pasting is still slow.

It seems the performance improvement is bound to the Ruby version and not the irb version. So please refactor this accordingly.

Please also update the CHANGELOG with notable changes (see https://github.com/makandra/geordi#contributing), and please print a message when using the flag:

```ruby
Interaction.note 'Using --no-multiline switch for faster pasting'
```
