### ISSUE TITLE
Link the Pivotal Tracker story with `geordi commit`

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#179]
The `geordi commit` currently [creates a commit](https://github.com/makandra/geordi/blob/master/lib/geordi/gitpt.rb#L24) with the following format if PT is connected:

```
title: "[##{story.id}] #{story.name}"
```

I suggest to add a direct link to the PT story within the commit description/body such as this:

```
title: [#123456] Reduce test flakyness
description: Story: https://www.pivotaltracker.com/story/show/123456
```

This brings various improvements:
* The merge request reviewer can easily access the story
* Fellow programmers get more context to a commit without searching for the story ID
* GitLab seems to prefer commits with a description

**Comment by codener** [comment]
Why not :+1:  I'll discuss it with the team and let you know our decision.

**Comment by codener** [comment]
We'll add it :+1:
