### ISSUE TITLE
Rename/Add commands

### ISSUE THREAD

**Issue by codener** [makandra/geordi#18]
- rename commands
  - geordi vnc
    - --setup
  - geordi firefox sets up firefox (instead of with_firefox_for_selenium)
    - --setup
  - cleanup-directory -> clean
  - deploy-to-production -> deploy
    - "source" branch, "deploy" branch, "deploy capistrano stage"
    - deploy branch default: first argument
    - deploy stage default: actual deploy branch

Option `--rerun` for `cucumber`, reruns tests while failing (max 3x)
Option `--debug` für `cucumber`, adds `--format pretty -b`

**Comment by henning-koch** [comment]
From our discussion: Another argument `--patiently` or similiar, to run Cucumber on everything and then re-run if there were failures.
