### ISSUE TITLE
Fuzzy find pivotal tracker stories

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#180]
Hi :wave: 

I'm using the `geordi branch` and `geordi commit` commands on a daily basis. They both list all `started` and `finished` stories for every linked pivotal tracker project - in my case up to 35 entries.

I would love geordi to use `fzf` to filter the commit list (if it is installed on my machine) instead of finding and typing out the desired number. The [current implementation](https://github.com/makandra/geordi/blob/master/lib/geordi/gitpt.rb#L102) relies on highline (which is not part of the gemspec :thinking:)

The implementation could be along these lines:

`printf "1. (Michael, finished) My current story\n2. (Michael, started) My other story" | fzf --header='Choose a story' --no-multi`

The number at the beginning of the line could be used by geordi to associate the result with the pivotal tracker story variable.

**Comment by codener** [comment]
As discussed: selecting a story already works, and long lists are rare. We're not sure the rather small benefit of using fzf justifies the added complexity. Closing the issue for now.
