### ISSUE TITLE
Make the `auto_update_chromedriver` option more obvious

### ISSUE THREAD

**Issue by niklas-hasselmeyer** [makandra/geordi#194]
The `auto_update_chromedriver` option is very useful. For new users, however, it's only not that obvious that this feature exists, as you have to read one specific part of the readme or get told by someone who knows.

I would like this option to get a little more obvious, I think it can be done as follows: 
When `geordi chromedriver-update` (or perhaps even `geordi cucumber`) is used and the `auto_update_chromedriver` option is not set or `nil`, ask the user if they want to enable automatic updates. If they say yes, write `auto_update_chromedriver: true` into the configuration file. If they say no, write `auto_update_chromedriver: false`.
For either response, Inform the user about the location of the config file.

What do you think?

**Comment by makandra-hq** [comment]
Thanks for the suggestion! We're already preparing a "did you know" feature that will cover this case as well.

**Comment by codener** [comment]
Covered in #198.
