### ISSUE TITLE
Update chromedriver update routine

### ISSUE THREAD

**Issue by codener** [makandra/geordi#200]
`ChromedriverUpdater` currently installs a chromedriver with the same version as Chrome. This strategy does not seem to hold any more, as [chromedriver announces](https://chromedriver.chromium.org/downloads):
> If you are using Chrome version 115 or newer, please consult[ the Chrome for Testing availability dashboard](https://googlechromelabs.github.io/chrome-for-testing/). This page provides convenient [JSON endpoints](https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json) for specific ChromeDriver version downloading.

Geordi will have to adopt the new way. However, we'll need to verify whether the new chromedriver-Chrome mapping will work with the normal Chrome, or require the [Chrome for Testing](https://googlechromelabs.github.io/chrome-for-testing/).

### Resources

- https://developer.chrome.com/blog/chrome-for-testing/
- https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints – chromedriver is included since v115.0.5763.0

**Comment by codener** [comment]
**Workaround:** Until Geordi is updated, you can manually update your chromedriver: Open https://googlechromelabs.github.io/chrome-for-testing/ > Section "Stable" > chromedriver / linux64 > Download ZIP from URL. Then take chromedriver from the ZIP file and put it e.g. into ~/bin/

**Comment by NiklasHae** [comment]
Hey @codener,
updating to `selenium-webdriver (4.11.0)` includes a feature that downloads drivers if they're missing, that's enabled by default (not sure if it's possible to disable, or if it would be a good idea to disable it).

It would probably make sense to think of a good upgrade path for the whole chromedriver issue, since it's unavoidable to update to newer selenium-webdriver version at some time in the future and both methods (geordi command, selenium-manager) should not conflict with each other. wdyt?

**Comment by codener** [comment]
Thanks for the notice, @NiklasHae. For the moment, Geordi will have to support projects that cannot upgrade their selenium-webdriver. However, any project that _can_ update should do it.

As for conflicts: the `chromedriver` binary installed by selenium-webdriver might be shadowed by the `chromedriver` installed by Geordi. **People who want to move away from Geordi maintaining `chromedriver` should disable the auto-updating** (`auto_update_chromedriver` in ~/.config/geordi/global.yml) **and remove the binary** (`which chromedriver`).

To fix Geordi, we should update `Geordi::ChromedriverUpdater` with download URLs from https://googlechromelabs.github.io/chrome-for-testing/latest-versions-per-milestone-with-downloads.json. [Docs](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints).
