### ISSUE TITLE
--multiline as option

### ISSUE THREAD

**Issue by c2ofh** [makandra/geordi#201]
Hey,

I would like to have `--multiline` disabled as default, when using `geordi shell *branch*`
The multiline option is sometimes usefull for pasting code, but often it causes strange problems. 

![image](https://github.com/makandra/geordi/assets/10913793/000d74bb-4e75-4351-9ce4-bb20e56aa377)

For some reasons assignments are are not working. 
When I start the console without --multiline, this issue never happens. 

Best

**Comment by codener** [comment]
Hi c2ofh. You have multiple options to work around this:
- Downgrade IRB to < 1.2
- Upgrade Ruby to >= 3.0
- [Use a workaround for assignments](https://github.com/stefankroes/ancestry/issues/531#issuecomment-1006912175)

We have not been able to reproduce the issues you describe. If none of these is feasible, please provide us a minimal reproduction example.

**Comment by codener** [comment]
@c2ofh just in case you're still seeing the error: [The fix is to update reline to 0.2.0+](https://github.com/stefankroes/ancestry/issues/531#issuecomment-1798289571).
