### ISSUE TITLE
Add support for Linear.app for `commit`-command

### ISSUE THREAD

**Issue by brunosedler** [makandra/geordi#218]
In the future we will be using [linear.app](https://linear.app/) to manage stories and issues. Therefore `geordi commit` should be able to use linear issue titles to generate commit messages.

There is a ruby cli tool for the linear API: https://github.com/rubyists/linear-cli

**Comment by makmic** [comment]
Minimal implementation suggestion (no dependencies)

Based on the graphql explorer https://studio.apollographql.com/public/Linear-API/variant/current/explorer 

```rb
def my_issue_titles(linear_team_key)
  filter = {
    "team": {
      "key": {
        "eq": linear_team_key,
      }
    },
    "assignee": {
      "isMe": {
        "eq": true
      }
    },
    "state": {
      "type": {
        "eq": "started"
      }
    }
  }
  response = request_with_payload(<<~GRAPHQL, filter:)
    query Issues($filter: IssueFilter) {
      issues(filter: $filter) {
        nodes {
          title
        }
      }
    }
  GRAPHQL

  response.dig(*%w[data issues nodes])&.map {|node| node['title'] }
end

API_ENDPOINT = 'https://api.linear.app/graphql'.freeze

def request_with_payload(attributes, variables)
  def client
  response = HTTP
   .headers({
      'Content-Type' => 'application/json',
      # API keys can be generated here: https://linear.app/makandra/settings/api
      'Authorization' => settings.linear_api_key
    })
   .post(API_ENDPOINT, json: { query: attributes.split.join(' '), variables: })
  @last_response = response
  parsed_response = JSON.parse(response.body)
  if parsed_response.key?('errors')
    raise parsed_response.dig('errors')
  else
    parsed_response['data']
  end
end
```

(I didn't test this particular code, ping me if you need further help)

**Comment by makmic** [comment]
Hi :wave: ,

could you give me some rough estimate or info on the implementation timeline for this (and its sibling) issue?

Thx!

**Comment by codener** [comment]
Closed by https://github.com/LisaHader/geordi/commit/13a4df48071e4a91fdf6f4dffd05fbb9fc8cba76.

**Comment by codener** [comment]
Hi @makmic – sorry, didn't see your question. This feature should be released this week.
