### ISSUE TITLE
Alias `geordi update-chromedriver` to `geordi chromedriver-update`

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#224]
Maybe it's just me, but I keep confusing `geordi chromedriver-update` with the (non-existent)  `geordi update-chromedriver` naming. I would not suggest changing the command name itself to avoid more confusion, but having an alias would save me some time in the future.

**Comment by codener** [comment]
Hi @makmic. The command name was chosen such that it has a unique prefix. You can invoke it with `geordi chrome`, for example. Notably, there already is an `update` command. If we renamed this command as suggested, you would need to at least type `geordi update-` to invoke this command.

Beyond that, how come you're frequently using that command? Can't you enable [automatic updates](https://github.com/makandra/geordi?tab=readme-ov-file#geordi-chromedriver-update)?

**Comment by makmic** [comment]
Okay. Sounds like a fair argument against the proposal, I'll close the issue! Thanks for the explanation.

Regarding automatic updates: I'm currently contributing to a codebase that does not use yarn but `pnpm` - I can't use `geordi rspec` as its "yarn install" hook breaks some stuff :grimacing:
