### ISSUE TITLE
Don't assume the default branch is named `master`

### ISSUE THREAD

**Issue by nhasselmeyer** [makandra/geordi#225]
A lot of commands in geordi still assume that the default git branch is named `master`, which is slightly outdated.

From grepping through the project, the affected commands are at least

- [X] `geordi security_update`
- [X] `geordi branch -m` (the long form of the argument should also be aliased as `--from-main`)
- [X] `geordi deploy`

As this makes the mentioned commands less useful or unusable in newer projects, these commands should check `git config init.defaultBranch` instead of using `master`.

**Comment by codener** [comment]
Thanks for the notification. We'll update accordingly.
