### ISSUE TITLE
Database port is not respected when loading a dump

### ISSUE THREAD

**Issue by foobear** [makandra/geordi#23]
When using a non-standard port (e.g. when using multiple PostgreSQL versions), geordi always tries to use the default port and a custom `port:` from `database.yml`

**Comment by kratob** [comment]
This has been fixed in 1.4.1 for postgres and 1.4.2 for mysql.

**Comment by kratob** [comment]
My bad, I misread. Was only fixed for `dumple` not for loading a dump.

**Comment by tessi** [comment]
This should be fixed since 1.6.2 (with @rin's commit), right?

**Comment by kratob** [comment]
Should be, yes.
