### ISSUE TITLE
How do you use this on Mac?

### ISSUE THREAD

**Issue by snoblenet** [makandra/geordi#25]
Georgi seems to depend on the Ubuntu-only package, vnc4server -- is that correct?

**Comment by henning-koch** [comment]
Sorry, none of us use Macs. Can't help you there.

**Comment by codener** [comment]
Geordi uses VNC to hide Selenium-controlled browser windows during Cucumber test runs. It should be usable without restrictions when vnc4server is missing.

I have been using Geordi on a Mac for years, and after putting medium effort into having Selenium windows hidden like on Ubuntu, I gave up. When I ran Selenium tests on my Mac, windows would pop up and steal focus, which was annoying. However, I got used to it.

So, you should be able to use Geordi on your Mac, but hiding Selenium windows is not possible.
