### ISSUE TITLE
passwords which include single or double quotes are not parsed correctly 

### ISSUE THREAD

**Issue by NatalieKrehan** [makandra/geordi#28]
For example
`geordi dump -l tmp/staging.dump`
returns 
`ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)`
for passwords which include single or double quotes.

**Comment by codener** [comment]
Closing stale issue.
Has happened once in years, and quotes in passwords are assumed to cause issues in other places as well. Also, shell-escaping the password is not simple because Ruby 1.8 has no `shellescape`.

If problem persists, please provide a PR.

**Comment by foobear** [comment]
Just FYI, Ruby 1.8 does have `shellescape`. You need `Shellwords` (stdlib).

```ruby
>> RUBY_VERSION
=> "1.8.7"
>> require 'shellwords'
=> true
>> Shellwords.escape('foo"bar baz')
=> "foo\\\"bar\\ baz"
>> 'foo"bar baz'.shellescape
=> "foo\\\"bar\\ baz"
```
