### ISSUE TITLE
Cannot load highline

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#35]
Ruby Version: ruby 2.4.1 installed with rvm
Geordi Version: Geordi 1.6.5

When calling e.g. `geordi dump` it says:

```
> Probably missing gem: highline
Install it now? [y] y
> ["gem install highline"]
Successfully installed highline-1.7.8
1 gem installed
> Retrying ...
/home/someuser/.rvm/gems/ruby-2.4.1/gems/geordi-1.6.5/lib/geordi/util.rb:29:in `require': cannot load such file -- highline (LoadError)
  from /home/someuser/.rvm/gems/ruby-2.4.1/gems/geordi-1.6.5/lib/geordi/util.rb:29:in `rescue in installing_missing_gems'
  from /home/someuser/.rvm/gems/ruby-2.4.1/gems/geordi-1.6.5/lib/geordi/util.rb:13:in `installing_missing_gems'
  from /home/someuser/.rvm/gems/ruby-2.4.1/gems/geordi-1.6.5/bin/geordi:5:in `<top (required)>'
  from /home/someuser/.rvm/gems/ruby-2.4.1/bin/geordi:22:in `load'
  from /home/someuser/.rvm/gems/ruby-2.4.1/bin/geordi:22:in `<main>'
  from /home/someuser/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
  from /home/someuser/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

`highline` is installed:

```
gem list |grep highline
highline (1.7.8)
```

**Comment by codener** [comment]
I suppose the issue is in https://github.com/makandra/geordi/blob/master/lib/geordi/util.rb#L29 where Geordi should actually require the `$1` from https://github.com/makandra/geordi/blob/master/lib/geordi/util.rb#L16.

**Comment by denzelem** [comment]
I will prepare a PR.

**Comment by denzelem** [comment]
**Issue**: Geordi was in the Gemfile of the project.
**How to solve**: 
- Remove geordi from the Gemfile.

or 

- Add geordi and highline to the Gemfile.

**Further explanation**:
`highline` is not in the gemspec as geordi has many dependencies which should not be loaded all in advanced. That way `geordi` will never see highline even if it is installed when execution in bundle context.
