### ISSUE TITLE
Capistrano Config: Settings in deploy/$stage.rb should take precedence over deploy.rb

### ISSUE THREAD

**Issue by triskweline** [makandra/geordi#36]
When the same config setting is defined both in `deploy.rb` and stage-specific files like `deploy/production.rb`, the stage-specific setting should take precedence.

Right now it's the other way round due to the implementation of https://github.com/makandra/geordi/blob/master/lib/geordi/capistrano_config.rb .

**Comment by codener** [comment]
@triskweline is this still an issue? Could you provide additional details?

**Comment by triskweline** [comment]
Yes, it's still an issue.

In the linked file we use regular expressions to find Capistrano without actually loading the recipe. For this we grep a string of Ruby code (`deploy_info`) that is concatenated from `deploy.rb` and `deploy/stage.rb` (in this order). Since the code then uses the first result from `=~`, `scan`, etc. we always get the generic config from `deploy.rb` rather than the more specific one from `deploy/stage.rb`.
