### ISSUE TITLE
Ignore ar_internal_metadata in geordi dump load

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#39]
Would it make sense to ignore ar_internal_metadata or set it to current Rails env after dump? Otherwise you always need to fix it manually after dump from staging or production.

**Comment by codener** [comment]
This is a good idea. Maybe a little hard to implement though. @triskweline what do you think?

**Comment by triskweline** [comment]
Implementation: I'm not sure what other things AR saves in that table, so I'm not sure if it's safe to ignore it entirely. We could run the `db:environment:set` task after a dump. But we would need to detect Rails 5+ first.

If we do this, I suggest to not do it automatically for production environments. It should be painful to load a production dump.

**Comment by codener** [comment]
Doesn't seem to be an issue any more. Closing.
