### ISSUE TITLE
Fix cuc output when running features in Chrome

### ISSUE THREAD

**Issue by thomasklemm** [makandra/geordi#4]
Since a few of our recent projects are running `cuc` features in Chrome, it would be nice if we could get rid of the message below.

```
No firefox version given, defaulting to 5.0.1.
Specify a version by putting it in a file named ".firefox-version".
```

**Comment by codener** [comment]
Simply add a `.firefox-version` file containing `system`. This will have Geordi use the system Firefox (and not a prepared Test-Firefox), but since you're using Chrome, Firefox won't be used at all.
