### ISSUE TITLE
Failed (parallel) test run is considered a success

### ISSUE THREAD

**Issue by foobear** [makandra/geordi#5]
After a (parallel) `geordi tests` run (project has RSpec + Cucumber), I get this output:

```
Failing Scenarios:
cucumber foo.feature:9 # Scenario: Foo
cucumber bar.feature:27 # Scenario: Bar

233 scenarios (2 failed, 231 passed)
3864 steps (1 failed, 22 skipped, 3841 passed)

Took 250.528129601 seconds

> Successfully ran tests.
```

It claims tests were successful while they failed.

Also (probably as a result of that), the exit code is 0 (success) which would not stop chained commands after a test run.

**Comment by codener** [comment]
The tests command itself relies on parallel_tests to return the correct exit code, so I believe that's the reason. 

Am 06.02.2015 um 15:13 schrieb Arne Hartherz <notifications@github.com>:

**Comment by codener** [comment]
I think I know what's wrong: `tests` calls `geordi test` with `system` and not `exec`, so the exit status gets lost. 


Am 06.02.2015 um 15:13 schrieb Arne Hartherz <notifications@github.com>:

**Comment by codener** [comment]
Similarly all other proxy binaries. 

Am 06.02.2015 um 15:13 schrieb Arne Hartherz <notifications@github.com>:

**Comment by henning-koch** [comment]
One more thing: By default [Thor exits with error 0 when there is a failure](https://github.com/erikhuda/thor/issues/244)

This sounds like a horrible default.  We could change this by this

```
class Geordi::CLI < Thor
  def self.exit_on_failure?
    true
  end
end
```

I'm not sure if this would negatively affect any scripts. I have seen at least one instance where we're abusing this: The `[tests command]`(https://github.com/makandra/geordi/blob/master/lib/geordi/commands/tests.rb) doesn't short-circuit if e.g. RSpec fails before Cucumber.

**Comment by henning-koch** [comment]
On the other side, it looks like @codener expected `tests` to short-circuit since he prints "Successfully ran tests" in the last line.

**Comment by codener** [comment]
For me, `geordi tests` has always failed early, as expected, when rspec or cucumber tests fail. 

Am 06.02.2015 um 16:44 schrieb Henning Koch <notifications@github.com>:

**Comment by codener** [comment]
Ok, this is probably not Geordi's fault. See https://github.com/cucumber/cucumber/issues/635.
