### ISSUE TITLE
Can we compress dumps before downloading?

### ISSUE THREAD

**Issue by triskweline** [makandra/geordi#52]
I am working on several projects that have MySQL dumps with hundreds of megabytes of data. I need to routinely copy them to my local machine for debugging. Doing this with `geordi dump` takes several minutes.

I wondered if we could compress dumps before downloading? We can assume that `tar` and `gzip` is available on both remote server and local machine.

I think we once had a failed PR about that somewhere, but I can't find it anymore.

**Comment by kratob** [comment]
Maybe using `scp -C` is enough? That should enable gzip compression in SSH.
