### ISSUE TITLE
Add current branch option to geordi to deploy 

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#56]
Geordi deploy should have an option to deploy from the current branch / feature branch instead of the pre-configured one (most often this is `master`). 

This should be possible with a command line argument for capistrano.

**Comment by codener** [comment]
Unfortunately, Capistrano 3 has dropped support for setting config variables from the command line (see https://stackoverflow.com/q/21027452/3497272).

Will set `DEPLOY_BRANCH` instead, and fail if it isn't used.
