### ISSUE TITLE
"geordi commit" fails connecting to Pivotal Tracker

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#65]
Since last week or so, `geordi commit` does no longer seem to be able connecting to the Pivotal Tracker API. 

### Backtrace:

```
Connecting to Pivotal Tracker...
/home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:223:in `exception_with_response': 404 Not Found (RestClient::NotFound)
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/abstract_response.rb:103:in `return!'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:809:in `process_result'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rest-client-2.0.2/lib/restclient/resource.rb:51:in `get'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pivotal-tracker-0.5.13/lib/pivotal-tracker/project.rb:14:in `find'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/gitpt.rb:107:in `block (2 levels) in load_projects'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/gitpt.rb:106:in `collect'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/gitpt.rb:106:in `block in load_projects'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/gitpt.rb:45:in `loading'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/gitpt.rb:105:in `load_projects'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/gitpt.rb:161:in `run'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/commands/commit.rb:5:in `commit'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/bin/geordi:10:in `block in <top (required)>'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/lib/geordi/util.rb:13:in `installing_missing_gems'
	from /home/foo/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/geordi-1.6.5/bin/geordi:5:in `<top (required)>'
	from /home/foo/.rbenv/versions/2.3.5/bin/geordi:23:in `load'
	from /home/foo/.rbenv/versions/2.3.5/bin/geordi:23:in `<main>'
```

Thanks for having a look.

**Comment by smith2martin** [comment]
FWIW, I'm using the pivotal-tracker-0.5.13 gem directly and have seen the same behavior starting about the same time. Potentially a place to start your investigation.

**Comment by smith2martin** [comment]
Here's my stack, identical other than a few gem versions.

/usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/abstract_response.rb:74:in `return!': 404 Resource Not Found (RestClient::ResourceNotFound)
	from /usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/request.rb:495:in `process_result'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/request.rb:421:in `block in transmit'
	from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/request.rb:413:in `transmit'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/request.rb:176:in `execute'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/rest-client-1.8.0/lib/restclient/resource.rb:51:in `get'
	from /usr/local/rvm/gems/ruby-2.1.5/gems/pivotal-tracker-0.5.13/lib/pivotal-tracker/project.rb:14:in `find'

**Comment by smith2martin** [comment]
Again FWIW, the below similarly results in a 404. Possible that Tracker made an API change recently that's causing this -- my tracker / github integration broke about the same time and I had to create a github integration on the tracker side to re-enable it.

`curl -X GET -H "X-TrackerToken: $TOKEN" "https://www.pivotaltracker.com/n/projects/XYZ`

**Comment by denzelem** [comment]
See https://github.com/jsmestad/pivotal-tracker/issues/122: API V3 and V4 are discontinued. Easiest way would be to migrate to https://github.com/dashofcode/tracker_api, but this drops support for Ruby < 2.1 for `geordi commit`.
