### ISSUE TITLE
Prefer bin/setup over geordi setup

### ISSUE THREAD

**Issue by denzelem** [makandra/geordi#69]
`geordi setup` has a set set of good defaults which need to be done before a project can run. But for some projects the defaults are not enough (e.g. elasticsearch setup is required). In this case a developer could use the Rails way and create a `bin/setup` file (this is already present since Rails 5). Geordi should then not execute its default `setup` but run `bin/setup`.

**Comment by kratob** [comment]
I would prefer option (1).
