### ISSUE TITLE
Catch interrupts (Ctrl + C)

### ISSUE THREAD

**Issue by codener** [makandra/geordi#7]
On interrupt, Geordi should not crash but `fail("Interrupted.")` instead.

**Comment by rlqualls** [comment]
I played around with this for a while and got a trap working in `bin/geordi` (`rescue Interrupt` on `Geordi::CLI.start` didn't work):

```ruby
#!/usr/bin/env ruby

require 'geordi/util'
include Geordi::Interaction

Geordi::Util.installing_missing_gems do
  require 'rubygems' unless defined?(Gem)
  require 'geordi'
  require 'thor'

  trap :INT do
    fail('Interrupted.')
  end

  Geordi::CLI.start
end
```

However, this will not catch the majority of interrupts, since most comments invoke `Geordi::Util::system!`, printing `"x Something went wrong."` Trapping and rescuing don't seem to work here, either.

```ruby
def system!(*commands)
  options = commands.last.is_a?(Hash) ? commands.pop : {}
  note_cmd commands.join(' ') if options[:show_cmd]

  if ENV['GEORDI_TESTING']
    puts "Util.system! #{ commands.join(' ') }"
  else
    # Remove Geordi's Bundler environment when running commands.
    Bundler.clean_system(*commands) or fail(options[:fail_message] || 'Something went wrong.')
  end
end
```

**Comment by codener** [comment]
Thanks for the effort you put into this. I just read [a bit about trapping shell signals](http://stackoverflow.com/questions/6108953/how-does-ctrl-c-terminate-a-child-process), but I currently don't have the time to elaborate on this further.

Maybe there's a chance to notice the interrupt from the parent process (`geordi`'s) and react properly when the child process (e.g. `cucumber`) returns a failure.

I would like a thorough solution catching all interrupts. If this is not possible, we should close the issue.

**Comment by codener** [comment]
Closing stale issue.
