### ISSUE TITLE
Simplify running tests in all supported Ruby versions

### ISSUE THREAD

**Issue by codener** [makandra/geordi#75]
Now that Geordi has automated tests, we should simplify running them in different Ruby versions. Especially Ruby 1.8.7 is frequently broken after pushing to `master`.

**Comment by codener** [comment]
Maybe the "update README" Rake task could be run as part of this.

**Comment by codener** [comment]
#79 might make this issue obsolete

**Comment by denzelem** [comment]
@codener I think this issue is separated from #79. You requirement will not be fulfilled once we add other versions than 2.6.5. At least 2.7.x will come in near future to prepare geordi for Ruby 3.

**Comment by codener** [comment]
It is hard to automate running tests in different Ruby versions (that's why [Gemika doesn't either](https://github.com/makandra/gemika#running-specs-in-multiple-ruby-versions)):

* The Ruby switching code needs to be compatible with various Ruby version managers
* All developers need to install the required Ruby versions
* Deciding on which Ruby versions to test:
  * Travis runs tests in many Ruby versions, so the developer does not need to
  * However, running tests locally in a very old and very recent Ruby may expose issue earlier than Travis would
  * As Ruby versions evolve, the list of testable Rubies should adapt

Because of these issues, I resorted to updating the contribution section of the README with simple instructions.
