### ISSUE TITLE
Resolve deprecation warning for "Bundler.clean_system"

### ISSUE THREAD

**Issue by makmic** [makandra/geordi#77]
Bundler 2.1.2 (https://github.com/bundler/bundler/commit/20dd6657062c650505b81343e49febd9ad9461ee) introduced a new helper `Bundler.unbundled_system` that replaces the `Bundler.clean_system` method. We should switch to the new method to get rid of the "major deprecation" notice.

**Comment by denzelem** [comment]
Thanks reporting this issues. It looks like we need a version switch for bundler, because older versions of bundler do not support `unbundled_system`.

**Comment by codener** [comment]
Thanks for fixing this. However, did you compare the two alternatives? 
> [DEPRECATED] `Bundler.clean_system` has been deprecated in favor of `Bundler.unbundled_system`. If you instead want to run the command in the environment before bundler was originally loaded, use `Bundler.original_system`.

I think `original_system` might be more appropriate here.

**Comment by denzelem** [comment]
I agree, `original_system` seems to be more appropriate here. I assume I misunderstood the deprecation warning.
