### ISSUE TITLE
Improve error message for `geordi console` when not bundled

### ISSUE THREAD

**Issue by kratob** [makandra/geordi#90]
Recently, I tried to connect to the console of a Rails 3.2 project and got the following error:

```
/var/www/<project>/shared/bundle/ruby/2.5.0/gems/railties-3.2.22.15/lib/rails/commands/console.rb:23:in `block in start': invalid option: -e (OptionParser::InvalidOption)
```

Turns out, I hadn't run `bundle install` on this machine, yet.

It is totally fine that `geordi console` will not work under those circumstance, but the error ist very misleading.

What happens is: Geordi tries to detect the Rails version to decide whether to run `rails c production` or `rails c -e production`. To do this, it calls `bundle list` (see https://github.com/makandra/geordi/blob/6c5c37323cd5ba42c4d968452a9080e98b42d939/lib/geordi/util.rb#L175), but does not check if that command errors out. In my case, `bundle list` returned an error message, and geordi proceeded to try and parse the Rails version from that error message.

I think printing a warning or aborting with an error would both be a good improvement.

**Comment by codener** [comment]
Since Geordi already includes functionality to bundle if required, the corresponding task should just be called prior to checking `bundle list` there.
